swagger: '2.0'
info:
  title: test
  version: 0.0.1
schemes:
  - http
basePath: /api
consumes:
  - application/json
produces:
  - application/json
paths:
  /employees/{employeeId}/start-date:
    get:
      tags: ["customers"]
      operationId: getStartDate
      summary: Get a start date for an employee
      parameters:
        - name: employeeId
          required: true
          in: path
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: date-time
        '401':
          description: unauthorized
          schema:
            $ref: "#/definitions/error"
        '404':
          description: resource not found
          schema:
            $ref: "#/definitions/error"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  error:
    type: object
    required:
       - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string

